#!/usr/bin/env node
/**
 * Bundle src/lib into the single Apps Script file library/Code.js.
 *
 * Apps Script libraries expose only top-level function declarations, so the
 * bundle is emitted as an IIFE under a private global and each export of
 * src/lib/index.ts gets a one-line top-level forwarding function appended.
 *
 *   npm run build            write library/Code.js
 *   npm run build -- --check exit 1 if library/Code.js is out of date
 */

import { build } from 'esbuild'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const ENTRY_FILE = join(REPO_ROOT, 'src', 'lib', 'index.ts')
const OUTPUT_FILE = join(REPO_ROOT, 'library', 'Code.js')
const BUNDLE_GLOBAL = '__OfflineDexLib'

/** Sorted names of everything src/lib/index.ts exports (each becomes a public library function). */
async function exportNames(): Promise<string[]> {
  const result = await build({
    entryPoints: [ENTRY_FILE],
    bundle: true,
    write: false,
    format: 'esm',
    metafile: true,
    logLevel: 'silent',
  })
  const outputs = Object.values(result.metafile.outputs)
  const names = outputs.flatMap((output) => output.exports ?? [])
  if (names.length === 0) throw new Error('No exports found in ' + ENTRY_FILE)
  return names.sort()
}

async function bundle(): Promise<string> {
  const names = await exportNames()
  const result = await build({
    entryPoints: [ENTRY_FILE],
    bundle: true,
    write: false,
    format: 'iife',
    globalName: BUNDLE_GLOBAL,
    target: 'es2020',
    platform: 'neutral',
    legalComments: 'none',
    banner: {
      js:
        '// GENERATED by scripts/build.ts from src/lib. Do not edit here.\n' +
        '// Public functions are the forwarding stubs at the bottom of this file.\n',
    },
    logLevel: 'silent',
  })
  const bundledCode = result.outputFiles[0]?.text ?? ''
  const forwardingStubs = names
    .map(
      (exportName) =>
        `/** OfflineDexLib.${exportName}; see src/lib/index.ts */\n` +
        `function ${exportName}() { return ${BUNDLE_GLOBAL}.${exportName}.apply(null, arguments) }`,
    )
    .join('\n')
  return bundledCode + '\n' + forwardingStubs + '\n'
}

async function main(): Promise<void> {
  const checkOnly = process.argv.includes('--check')
  const bundled = await bundle()
  if (checkOnly) {
    const onDisk = existsSync(OUTPUT_FILE)
      ? readFileSync(OUTPUT_FILE, 'utf8')
      : ''
    if (onDisk !== bundled) {
      console.error(`  ✗ ${OUTPUT_FILE} is out of date; run \`npm run build\``)
      process.exitCode = 1
      return
    }
    console.log('  ✓ library/Code.js is up to date')
    return
  }
  writeFileSync(OUTPUT_FILE, bundled)
  const sizeKb = (Buffer.byteLength(bundled) / 1024).toFixed(1)
  console.log(`  ✓ wrote library/Code.js (${sizeKb} kB)`)
}

main().catch((error: unknown) => {
  console.error(error)
  process.exitCode = 1
})
