#!/usr/bin/env node
/**
 * Bundle src/lib into the single Apps Script file library/Code.js.
 *
 * Apps Script libraries expose only top-level function declarations, so the
 * bundle is emitted as an IIFE under a private global and each export of
 * src/lib/index.ts gets a one-line top-level forwarding function appended.
 *
 *   npm run build            write library/Code.js
 *   npm run build -- --check exit 1 if library/Code.js is out of date
 */

import { build } from 'esbuild'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const ENTRY = join(REPO_ROOT, 'src', 'lib', 'index.ts')
const OUT = join(REPO_ROOT, 'library', 'Code.js')
const GLOBAL = '__OfflineDexLib'

async function exportNames(): Promise<string[]> {
  const result = await build({
    entryPoints: [ENTRY],
    bundle: true,
    write: false,
    format: 'esm',
    metafile: true,
    logLevel: 'silent',
  })
  const outputs = Object.values(result.metafile.outputs)
  const names = outputs.flatMap((o) => o.exports ?? [])
  if (names.length === 0) throw new Error('No exports found in ' + ENTRY)
  return names.sort()
}

async function bundle(): Promise<string> {
  const names = await exportNames()
  const result = await build({
    entryPoints: [ENTRY],
    bundle: true,
    write: false,
    format: 'iife',
    globalName: GLOBAL,
    target: 'es2020',
    platform: 'neutral',
    legalComments: 'none',
    banner: {
      js:
        '// GENERATED by scripts/build.ts from src/lib — do not edit here.\n' +
        '// Public functions are the forwarding stubs at the bottom of this file.\n',
    },
    logLevel: 'silent',
  })
  const code = result.outputFiles[0]?.text ?? ''
  const stubs = names
    .map(
      (n) =>
        `/** OfflineDexLib.${n} — see src/lib/index.ts */\n` +
        `function ${n}() { return ${GLOBAL}.${n}.apply(null, arguments) }`,
    )
    .join('\n')
  return code + '\n' + stubs + '\n'
}

async function main(): Promise<void> {
  const check = process.argv.includes('--check')
  const out = await bundle()
  if (check) {
    const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : ''
    if (current !== out) {
      console.error(`  ✗ ${OUT} is out of date — run \`npm run build\``)
      process.exitCode = 1
      return
    }
    console.log('  ✓ library/Code.js is up to date')
    return
  }
  writeFileSync(OUT, out)
  const kb = (Buffer.byteLength(out) / 1024).toFixed(1)
  console.log(`  ✓ wrote library/Code.js (${kb} kB)`)
}

main().catch((e: unknown) => {
  console.error(e)
  process.exitCode = 1
})
